services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: avaliacao_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api-service:
    build: ./api-service
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
      - db

  worker-service:
    build: ./worker-service
    depends_on:
      - rabbitmq

volumes:
  postgres_data: